project:
  type: book

book:
  title: "paper"
  author: "Tomás Urzúa & Juan Carlos Castillo"
  date: "20-06-2025"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd

bibliography: invalsi.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

