project:
  type: book

book:
  title: "paper"
  author: "Tomás Urzúa"
  author: "Juan Carlos Castillo"
  date: "20-06-2025"
  chapters:
    - abstract.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

