project:
  type: book

book:
  title: "Digital Literacy and the Digital Divide: Multilevel Analysis of Individual, School, and Country Factors Using ICILS Data"
  author: "Tomás Urzúa & Juan Carlos Castillo"
  date: "20-06-2025"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd

bibliography: invalsi-icils.bib

format:
  docx: 
    number-sections: true
#  html:
#    theme: cosmo    

editor: source

